name: Build Extension

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Ant
      run: sudo apt-get update && sudo apt-get install -y ant

    - name: Build with Ant
      run: ant -buildfile appinventor/build.xml extensions
      env:
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        # Upload the AIX files
        name: aix
        path: "appinventor/components/aix/*.aix"
